name: healthAndBeauty
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  animated_notch_bottom_bar: ^1.0.3
  bot_toast: ^4.1.3
  cached_network_image: ^3.4.1
  change_app_package_name: ^1.5.0
  chewie: ^1.7.1
  chucker_flutter:
    git:
      url: https://github.com/syedmurtaza108/chucker-flutter.git
      ref: master
  country_picker: ^2.0.27
  cupertino_icons: ^1.0.8
  device_info_plus: ^11.5.0
  device_preview: ^1.2.0
  dio: ^5.8.0+1
  dropdown_button2: ^2.3.9
  easy_localization: ^3.0.7+1
  equatable: ^2.0.7
  file_picker: ^10.2.0
  flutter:
    sdk: flutter
  flutter_ar_json_extractor: ^0.0.6
  flutter_bloc: ^9.1.1
  flutter_native_splash: null
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.9.3
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.1.0
  fluttertoast: ^8.2.12
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  http_parser: ^4.0.2
  image_picker: ^1.1.2
  image_sequence_animator: null
  mime: ^2.0.0
  open_filex: ^4.7.0
  path: any
  path_provider: ^2.1.5
  pdf: ^3.11.3
  percent_indicator: ^4.2.5
  permission_handler: ^12.0.1
  photo_view: ^0.15.0
  pinput: ^5.0.1
  pretty_dio_logger: ^1.4.0
  persistent_bottom_nav_bar: ^6.2.1
  printing: ^5.14.2
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  skeletonizer: ^1.4.3
  smooth_page_indicator: ^1.2.1
  text_style: ^0.0.2
  table_calendar: ^3.1.3
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/png/
    - assets/images/svg/
    - assets/translation/
    - assets/fonts/
    - assets/

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Cairo-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Cairo-Black.ttf
          weight: 900

flutter_assets:
  assets_path: assets/images
  output_path: lib/core/assets/images/
  filename: app_images.dart
  class_name: AppImages
  field_prefix: null
